// The 109-type list from the third trial run, kept for comparison. Worse than v49 in aggregate; see compare output.
'use strict';
module.exports = {
  title: "The title of the page or article itself: the single main heading, usually the largest text and near the top.",
  heading: "A section or subsection heading within the content: short, sets up what follows, not the page title.",
  summary: "A standfirst, lede, abstract, deck, or TL;DR: a few sentences summarising the content, placed before the body.",
  key_points: "A short bulleted list of takeaways or highlights placed before or after the body: key points, at a glance, what you need to know.",
  text: "Running prose the reader came to read: paragraphs of an article, an answer, a description, a story, documentation.",
  byline: "Who wrote it and when: author name, publication date, updated date, reading time, source attribution, dateline.",
  author_bio: "A box about the author placed after the content: photo, short biography, links to their other work.",
  metadata: "Facts about the item shown as labelled values: tags, categories, prep time, servings, difficulty, version, licence, file size, word count.",
  badge: "A small status label attached to content: new, updated, verified, beta, deprecated, widely available, editor's pick.",
  correction: "An editorial note that the content was corrected, updated, or clarified after publication, or an editor's note.",
  disclosure: "A statement that the content contains affiliate links, was sponsored, or that the author has a conflict of interest.",
  content_warning: "A notice that the content may be upsetting, explicit, or unsuitable for some readers, placed before it.",
  image: "A single still image or illustration that is part of the content, with or without a caption.",
  gallery: "Several content images shown together as a set: a gallery, a slideshow of photos, a row of figures.",
  chart: "A static chart, graph, diagram, or infographic that is part of the content, as an image or inline SVG.",
  video: "A video player or embedded video that is part of the content.",
  audio: "An audio player or podcast episode that is part of the content.",
  transcript: "The written transcript of a video, podcast, or interview, usually with speaker names or timestamps.",
  table: "Tabular data: rows and columns of values, a comparison grid, a spec sheet, a timetable, a compatibility matrix.",
  list: "A list that is content: bullet points, ingredients, features, a list of items without a fixed order.",
  steps: "An ordered sequence of instructions the reader follows in order: method, procedure, tutorial steps, numbered directions.",
  definition_list: "Terms paired with their definitions: a glossary, a parameter list, a list of fields with descriptions.",
  faq: "Questions paired with their answers: a frequently-asked-questions section, a Q&A.",
  timeline: "Events in date order presented as a timeline or chronology, each with a date and a description.",
  quote: "A quotation set apart from the prose: a blockquote, a pull quote, an epigraph.",
  code: "A code sample, terminal output, configuration, or other preformatted text meant to be read literally.",
  code_output: "The result of running a code sample, shown beside or beneath it: console output, a rendered result, a notebook cell output.",
  math: "A displayed mathematical formula or equation.",
  callout: "A boxed note, tip, warning, or important notice inside the content flow that the author set apart.",
  infobox: "A summary panel of key facts about the subject, usually at the side or top: an encyclopedia infobox, a key-facts box, a recipe overview panel, a knowledge panel.",
  footnote: "Footnotes or endnotes: numbered notes referred to from the text, shown at the bottom.",
  references: "A bibliography, citation list, sources, or works cited: the list of things the content cites.",
  table_of_contents: "A list of links to sections within this same page: \"In this article\", \"Contents\", \"Jump to\".",
  accordion: "Collapsible sections the reader expands one at a time to reveal content: expandable headings, show/hide details, a FAQ built as expanders.",
  tabs: "A strip of tabs or toggles within the content that switch which part of it is shown: Ingredients | Nutrition, Overview | Specs | Reviews, Metric | US.",
  embed: "An interactive widget embedded in the content that runs as built: a live code sample, an interactive chart, a calculator, a social media post, a playground.",
  map: "An interactive or static map showing a location or area as part of the content.",
  poll: "A poll, survey, or quiz the reader answers, with results or a score.",
  calendar: "Event details or a calendar: date, time, venue, add-to-calendar, schedule of sessions.",
  contact_details: "An address, phone number, email address, opening hours, or a contact card for a person or organisation.",
  download: "A link or button to download a file that is the content: a PDF, a dataset, an installer, an attachment.",
  comments: "User comments, replies, or a discussion thread beneath or beside the main content.",
  reviews: "User reviews of a product, place, or service, each with a rating and text.",
  rating: "An aggregate rating or vote display: stars, score out of ten, number of ratings, upvote count, like count.",
  reactions: "Emoji or one-click reactions on a piece of content: like, love, thumbs up, clap, and their counts.",
  vote_controls: "Controls for the reader to vote on an item: upvote and downvote arrows, thumbs up and down, helpful yes/no.",
  post_header: "The header of one post in a forum or thread: username, avatar, post date, post number, user rank.",
  user_card: "A profile card for a user: avatar, name, handle, follower count, join date, bio, follow button.",
  related: "Links to other content on the same site chosen for this page: related articles, see also, you might also like, more from this author, more in this series.",
  teaser_card: "A repeated card or list item that previews another page: headline plus a summary, image, or timestamp, linking to the full item. The unit of news indexes, search results, product listings, and recipe collections.",
  product_card: "A repeated card previewing a product for sale: image, name, price, rating, add-to-cart, linking to the product page. The unit of shop listings and search results in a store.",
  trending: "A ranked list of what is popular on the site right now: most read, trending, top stories, hot topics.",
  tag_cloud: "A set of topic tags or categories to browse by, shown as chips or a cloud.",
  archive_nav: "Links to browse content by date: months, years, an archive list, a date picker for past issues.",
  pagination: "Controls to move between pages of a listing or thread: page numbers, next, previous, load more, older, newer.",
  external_links: "Links out to other websites presented as a list: official site, further reading elsewhere, download mirrors.",
  sitelinks: "A row of links to important sections of a site, shown beneath a search result or in a site overview.",
  form: "A form the reader fills in and submits as part of using the content: sign up, comment box, contact form, settings, application.",
  login_form: "A form to sign in or register: username, password, social sign-in buttons, forgot password.",
  search: "A search box: site search, filter input, find within this section.",
  filters: "Controls that narrow a listing: facets, checkboxes by brand or category, price range, date range, sort order, results count.",
  action_button: "A button or small control that acts on the current item: save, print, download, play, copy, bookmark, follow, expand, read more.",
  buy_box: "The purchase panel for a product: price, quantity, variants, add to cart or buy now, delivery estimate, stock status.",
  cart: "The shopping cart or basket contents: items, quantities, subtotal, proceed to checkout.",
  checkout: "A checkout or payment step: delivery address, payment method, order summary, place order.",
  pricing_table: "Plans compared side by side with prices and features: free, pro, enterprise; monthly, yearly.",
  settings: "Preferences the reader changes for themselves: theme toggle, font size, language, notifications, units, accessibility options.",
  site_header: "The site masthead: logo, site name, top bar, the strip at the very top that identifies the site.",
  site_nav: "The site-wide navigation menu: main sections, primary menu, hamburger menu contents, a mega menu.",
  section_nav: "Navigation within a section of the site: a sidebar tree of pages in the docs, a category submenu, chapter list, previous and next page.",
  breadcrumbs: "The trail of links showing where this page sits in the site: Home > Recipes > Cakes.",
  version_switcher: "A control to pick which version, edition, language, or platform of the documentation to view.",
  page_tools: "Tools that act on the page as an object rather than its content: edit, history, view source, print view, cite this page, report a problem, translate.",
  feedback: "A prompt asking whether the page was helpful or how to improve it: thumbs up/down, \"was this page useful\", rate this page.",
  account: "Sign-in link, profile, account menu, notifications bell, cart icon in the header: the reader's relationship with the site.",
  share: "Buttons to share the page on social networks, copy the link, email it.",
  site_footer: "The site-wide footer: about, contact, legal links, copyright, sitemap, social links at the bottom of every page.",
  legal_notice: "Terms, disclaimer, privacy, or copyright text shown as content on the page rather than as footer links.",
  skip_link: "Accessibility links such as skip to content, back to top, or jump to navigation.",
  site_notice: "A site-wide announcement bar at the top: breaking news, maintenance, a sale, a new feature, a fundraising appeal.",
  cookie_banner: "A cookie consent, privacy notice, or GDPR banner asking the reader to accept or manage tracking.",
  consent_gate: "A placeholder where embedded content is withheld until the reader consents: \"this content is hosted by a third party\".",
  age_gate: "A prompt asking the reader to confirm their age or region before seeing the content.",
  popup: "A modal or overlay that interrupts the page and must be dismissed: an exit-intent popup, a welcome dialog, a survey prompt.",
  sticky_bar: "A bar fixed to the top or bottom of the viewport that stays while scrolling: a persistent call to action, a reading progress bar with links, a mini player.",
  chat_widget: "A customer support chat bubble, chatbot launcher, or live chat panel.",
  ad: "An advertisement: a display ad, an ad slot, sponsored product placement from a third party.",
  sponsored: "Content presented like articles but paid for: sponsored posts, promoted stories, partner content, affiliate product picks.",
  newsletter: "A prompt to subscribe to a newsletter or email list.",
  subscribe: "A prompt to subscribe to, pay for, or upgrade the site itself: membership, premium, support us, donate.",
  paywall: "A notice that the content is limited or hidden until the reader pays or logs in, including \"you have N free articles left\".",
  app_nag: "A prompt to install or open the site's mobile app, or to enable push notifications.",
  cross_promo: "Promotion of the site's own other products, events, or services: our podcast, our shop, our conference, sister sites.",
  hero: "The large banner at the top of a landing or product page: a headline, a subheading, a background image, and a primary call to action.",
  feature_grid: "A grid of features or benefits, each with an icon, a short title, and a sentence.",
  cta: "A call-to-action block: a headline and a button asking the reader to sign up, get started, try free, or contact sales.",
  testimonial: "Quotes from customers or users praising the product, with names, photos, or company logos.",
  logo_cloud: "A row of customer, partner, or press logos: \"trusted by\", \"as seen in\".",
  stats: "Big numbers as claims: users served, countries, uptime, years in business.",
  team: "Cards for people: team members, speakers, contributors, authors on staff, each with a photo, name, and role.",
  dashboard_widget: "A panel in a dashboard showing a metric, a small chart, or a status: a KPI tile, a gauge, a recent-activity feed.",
  data_grid: "An interactive table of records the user works with: sortable, filterable rows of issues, orders, files, emails, users.",
  toolbar: "A row of tools or controls for operating an application: drawing tools, formatting buttons, canvas actions, a command bar.",
  canvas: "The working surface of an application: a drawing canvas, a map viewport, a document editor, a spreadsheet grid, a game board.",
  status_message: "A transient message about the system: success, error, loading, saved, offline, a toast or alert.",
  empty_state: "A message shown where content would be but none exists yet: no results, nothing here, get started by adding one.",
  progress: "A stepper or progress indicator showing where the reader is in a multi-step process: step 2 of 4, checkout stages.",
  decoration: "A purely visual element with no content: spacer, divider, background image, decorative icon, empty container.",
  unclear: "None of the above fits, or the region mixes several types so evenly that no one type describes it."
};
